# Generated by Django 6.1.1 on 2026-09-25 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_limit_identity_document_length"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
