# Generated by Django 6.1.1 on 2026-09-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_delete_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="refreshsession",
            name="accounts_re_user_id_0a6231_idx",
        ),
        migrations.DeleteModel(
            name="RefreshSession",
        ),
    ]
