# Generated by Django 6.1.1 on 2026-09-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_delete_refreshsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="failed_login_attempts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="locked_until",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lockout_level",
        ),
    ]
