# Generated by Django 6.1.1 on 2026-09-27 16:13

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_failed_login_attempts_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("producers", "0007_enable_unaccent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("users_view", "Puede consultar cuentas"),
                    ("users_create", "Puede crear cuentas"),
                    ("users_update", "Puede actualizar cuentas"),
                    ("users_change_status", "Puede activar o desactivar cuentas"),
                    ("association_access_manage", "Puede administrar el acceso de la asociación"),
                ]
            },
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{7,10}\\Z", "El teléfono debe contener solo entre 7 y 10 dígitos."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="producer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="producers.producer",
            ),
        ),
        migrations.CreateModel(
            name="AccountManagementEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("account_created", "Cuenta creada"),
                            ("account_activated", "Cuenta activada"),
                            ("account_deactivated", "Cuenta desactivada"),
                            ("account_reactivated", "Cuenta reactivada"),
                            ("account_roles_changed", "Roles de la cuenta cambiados"),
                            ("role_created", "Rol creado"),
                            ("role_updated", "Rol actualizado"),
                            ("role_deleted", "Rol borrado"),
                            ("association_access_enabled", "Acceso de la asociación habilitado"),
                            (
                                "association_access_disabled",
                                "Acceso de la asociación deshabilitado",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_role_id", models.UUIDField(blank=True, null=True)),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="AssociationAccess",
            fields=[
                (
                    "producer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="association_access",
                        serialize=False,
                        to="producers.producer",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fixed", "Fijo"),
                            ("predefined", "Predefinido"),
                            ("custom", "Propio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role",
                        to="auth.group",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="producers.producer",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("roles_view", "Puede consultar roles y el catálogo de permisos"),
                    ("roles_manage", "Puede crear, editar y borrar roles propios"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        condition=models.Q(("producer__isnull", True)),
                        name="accounts_role_system_name_ci_unique",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        models.F("producer"),
                        condition=models.Q(("producer__isnull", False)),
                        name="accounts_role_producer_name_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "custom"), ("producer__isnull", False)),
                            models.Q(
                                models.Q(("kind", "custom"), _negated=True),
                                ("producer__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="accounts_role_producer_matches_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("code__isnull", True), ("kind", "custom")),
                            models.Q(
                                models.Q(("kind", "custom"), _negated=True),
                                ("code__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="accounts_role_code_matches_kind",
                    ),
                ],
            },
        ),
    ]
