# Generated by Django 6.1.1 on 2026-09-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_options_user_phone_user_producer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["name", "id"],
                "permissions": [
                    ("roles_view", "Puede consultar roles y el catálogo de permisos"),
                    ("roles_manage", "Puede crear, editar y borrar roles propios"),
                ],
            },
        ),
    ]
