# Generated by Django 6.1.1 on 2026-09-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_role_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name", "first_name", "id"],
                "permissions": [
                    ("users_view", "Puede consultar cuentas"),
                    ("users_create", "Puede crear cuentas"),
                    ("users_update", "Puede actualizar cuentas"),
                    ("users_change_status", "Puede activar o desactivar cuentas"),
                    ("association_access_manage", "Puede administrar el acceso de la asociación"),
                ],
            },
        ),
    ]
