# Generated by Django 6.1.1 on 2026-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_delete_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmanagementevent",
            name="target_user_ref",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountmanagementevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("account_created", "Cuenta creada"),
                    ("account_activated", "Cuenta activada"),
                    ("account_deactivated", "Cuenta desactivada"),
                    ("account_reactivated", "Cuenta reactivada"),
                    ("account_deleted", "Cuenta eliminada"),
                    ("account_roles_changed", "Roles de la cuenta cambiados"),
                    ("role_created", "Rol creado"),
                    ("role_updated", "Rol actualizado"),
                    ("role_deleted", "Rol borrado"),
                    ("association_access_enabled", "Acceso de la asociación habilitado"),
                    ("association_access_disabled", "Acceso de la asociación deshabilitado"),
                ],
                max_length=32,
            ),
        ),
    ]
