# Generated by Django 6.1.1 on 2026-10-05 21:55

from django.db import migrations, models


def delete_switch_rows(apps, schema_editor):
    """Las filas del interruptor son rastro de una función que ya no existe: se borran."""
    event = apps.get_model("accounts", "AccountManagementEvent")
    event.objects.filter(
        event_type__in=["association_access_enabled", "association_access_disabled"]
    ).delete()
    # Django no retira los permisos que ya no declara ningún modelo: sin esto el grupo del rol
    # Productor lo seguiría teniendo.
    permission = apps.get_model("auth", "Permission")
    permission.objects.filter(
        content_type__app_label="accounts", codename="association_access_manage"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_account_deleted_event"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(delete_switch_rows, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name", "first_name", "id"],
                "permissions": [
                    ("users_view", "Puede consultar cuentas"),
                    ("users_create", "Puede crear cuentas"),
                    ("users_update", "Puede actualizar cuentas"),
                    ("users_change_status", "Puede activar o desactivar cuentas"),
                    ("users_delete", "Puede eliminar cuentas creadas por error"),
                ],
            },
        ),
        migrations.AlterField(
            model_name="accountmanagementevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("account_created", "Cuenta creada"),
                    ("account_activated", "Cuenta activada"),
                    ("account_deactivated", "Cuenta desactivada"),
                    ("account_reactivated", "Cuenta reactivada"),
                    ("account_deleted", "Cuenta eliminada"),
                    ("account_roles_changed", "Roles de la cuenta cambiados"),
                    ("role_created", "Rol creado"),
                    ("role_updated", "Rol actualizado"),
                    ("role_deleted", "Rol borrado"),
                ],
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="AssociationAccess",
        ),
    ]
