# Generated by Django 6.1.1 on 2026-09-21 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("member_code", models.CharField(editable=False, max_length=11, unique=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CC", "C?dula de ciudadan?a"),
                            ("CE", "C?dula de extranjer?a"),
                            ("PPT", "Permiso por Protecci?n Temporal"),
                            ("NIT", "N?mero de Identificaci?n Tributaria"),
                        ],
                        max_length=3,
                    ),
                ),
                ("identity_document", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=25, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("municipality_code", models.CharField(max_length=20)),
                ("joined_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("inactive", "Inactivo")],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "municipality_code"],
                        name="producers_p_status_60d832_idx",
                    ),
                    models.Index(
                        fields=["last_name", "first_name", "id"],
                        name="producers_p_last_na_bc36ab_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "identity_document"),
                        name="producers_document_type_number_unique",
                    )
                ],
            },
        ),
    ]
