# Generated by Django 6.1.1 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producers", "0003_alter_producer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="identity_document",
            field=models.CharField(max_length=15),
        ),
    ]
