# Generated by Django 6.1.1 on 2026-09-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0004_alter_producer_identity_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de ciudadanía"),
                    ("CE", "Cédula de extranjería"),
                    ("PPT", "Permiso por Protección Temporal"),
                    ("NIT", "Número de Identificación Tributaria"),
                ],
                max_length=3,
            ),
        ),
    ]
