# Generated by Django 6.1.1 on 2026-10-09 12:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producers", "0009_producer_audit_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgriculturalInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("name_normalized", models.CharField(editable=False, max_length=240)),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("fertilizer", "Fertilizante"),
                            ("organic_fertilizer", "Abono"),
                            ("fungicide", "Fungicida"),
                            ("insecticide", "Insecticida"),
                            ("other", "Otro"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogramos"),
                            ("g", "Gramos"),
                            ("l", "Litros"),
                            ("ml", "Mililitros"),
                            ("unit", "Unidades"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sack", "Bulto"),
                            ("bag", "Bolsa"),
                            ("tub", "Pote"),
                            ("flask", "Frasco"),
                            ("bottle", "Botella"),
                            ("gallon", "Galón"),
                            ("drum", "Caneca"),
                            ("box", "Caja"),
                            ("sachet", "Sobre"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "package_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001")),
                            django.core.validators.MaxValueValidator(Decimal("100000")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agricultural_inputs",
                        to="producers.producer",
                    ),
                ),
            ],
            options={
                "ordering": ["name_normalized"],
                "permissions": [
                    ("view_agriculturalinput", "Puede consultar insumos agrícolas"),
                    ("add_agriculturalinput", "Puede registrar insumos agrícolas"),
                    (
                        "change_agriculturalinput",
                        "Puede editar, activar y desactivar insumos agrícolas",
                    ),
                    (
                        "delete_agriculturalinput",
                        "Puede eliminar insumos agrícolas creados por error",
                    ),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AgriculturalInputAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("input_ref", models.UUIDField(db_index=True)),
                ("input_name", models.CharField(max_length=80)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Insumo registrado"),
                            ("updated", "Insumo actualizado"),
                            ("status_changed", "Estado de insumo modificado"),
                            ("deleted", "Insumo eliminado"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("changes", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agricultural_input_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "input",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="inputs.agriculturalinput",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="agriculturalinput",
            constraint=models.UniqueConstraint(
                fields=("producer", "input_type", "name_normalized"),
                name="inputs_input_producer_type_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="agriculturalinput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("package_size__isnull", False), ("package_type__isnull", False)),
                    models.Q(("package_size__isnull", True), ("package_type__isnull", True)),
                    _connector="OR",
                ),
                name="inputs_input_package_both_or_none",
            ),
        ),
        migrations.AddConstraint(
            model_name="agriculturalinput",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("package_size__gte", Decimal("0.001")),
                        ("package_size__lte", Decimal("100000")),
                    ),
                    ("package_size__isnull", True),
                    _connector="OR",
                ),
                name="inputs_input_package_size_range",
            ),
        ),
    ]
