# Generated by Django 6.1.1 on 2026-10-09 13:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_farm_deletion_and_surviving_audit"),
        ("inputs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InputMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("entry", "Entrada"),
                            ("count", "Conteo"),
                            ("consumption", "Salida por actividad"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "counted_quantity",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                ("occurred_on", models.DateField()),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="input_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="input_movements",
                        to="farms.farm",
                    ),
                ),
                (
                    "input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inputs.agriculturalinput",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-created_at", "-id"],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["input", "farm", "occurred_on", "created_at"],
                        name="inputs_mov_input_farm_date_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "entry"), _negated=True),
                            ("quantity__gt", 0),
                            _connector="OR",
                        ),
                        name="inputs_movement_entry_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "consumption"), _negated=True),
                            ("quantity__lt", 0),
                            _connector="OR",
                        ),
                        name="inputs_movement_consumption_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("counted_quantity__gte", 0),
                                ("counted_quantity__isnull", False),
                                ("kind", "count"),
                            ),
                            models.Q(
                                models.Q(("kind", "count"), _negated=True),
                                ("counted_quantity__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="inputs_movement_counted_iff_count",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InputStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=12),
                ),
                ("last_count_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="input_stocks",
                        to="farms.farm",
                    ),
                ),
                (
                    "input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stocks",
                        to="inputs.agriculturalinput",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "manage_inputstock",
                        "Puede registrar entradas y conteos de inventario de insumos",
                    )
                ],
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("input", "farm"), name="inputs_stock_input_farm_unique"
                    )
                ],
            },
        ),
    ]
