# Generated by Django 6.1.1 on 2026-10-02 00:35

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0004_farm_permission_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("code_normalized", models.CharField(editable=False, max_length=200)),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[apps.common.validators.validate_positive_area],
                    ),
                ),
                ("boundary", models.JSONField(blank=True, null=True)),
                (
                    "measured_area_hectares",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plots",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_plot", "Puede consultar parcelas"),
                    ("add_plot", "Puede registrar parcelas"),
                    ("change_plot", "Puede editar, activar y desactivar parcelas"),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlotAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Parcela creada"),
                            ("updated", "Parcela actualizada"),
                            ("status_changed", "Estado de parcela modificado"),
                        ],
                        max_length=32,
                    ),
                ),
                ("area_hectares", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "measured_area_hectares",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plot_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="plots.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="plot",
            constraint=models.UniqueConstraint(
                fields=("farm", "code_normalized"), name="plots_farm_code_normalized_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="plot",
            constraint=models.CheckConstraint(
                condition=models.Q(("area_hectares__gt", 0)), name="plots_area_hectares_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="plot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("boundary__isnull", True), ("measured_area_hectares__isnull", True)),
                    models.Q(
                        ("boundary__isnull", False), ("measured_area_hectares__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="plots_boundary_with_measured_area",
            ),
        ),
    ]
