# Generated by Django 6.1.1 on 2026-09-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0002_member_code_sequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producer",
            options={
                "ordering": ["last_name", "first_name", "id"],
                "permissions": [
                    ("view", "Puede consultar productores"),
                    ("create", "Puede crear productores"),
                    ("update", "Puede actualizar productores"),
                    ("change_status", "Puede cambiar el estado de productores"),
                ],
            },
        ),
    ]
