# Generated by Django 6.1.1 on 2026-09-25 04:39

import apps.common.municipalities
import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0005_alter_producer_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producer",
            name="identity_document",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{6,15}\\Z",
                        "El número de documento debe contener solo dígitos, entre 6 y 15.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="joined_on",
            field=models.DateField(validators=[apps.common.validators.validate_not_future]),
        ),
        migrations.AlterField(
            model_name="producer",
            name="municipality_code",
            field=models.CharField(
                max_length=20, validators=[apps.common.municipalities.validate_municipality_code]
            ),
        ),
        migrations.AlterField(
            model_name="producer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{7,10}\\Z", "El teléfono debe contener solo entre 7 y 10 dígitos."
                    )
                ],
            ),
        ),
    ]
