# Generated by Django 6.1.1 on 2026-10-03 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producers", "0008_producer_delete_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProducerAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("member_code", models.CharField(db_index=True, max_length=11)),
                ("producer_name", models.CharField(max_length=200)),
                (
                    "action",
                    models.CharField(choices=[("deleted", "Productor eliminado")], max_length=16),
                ),
                ("farms_deleted", models.PositiveIntegerField(default=0)),
                ("accounts_deleted", models.PositiveIntegerField(default=0)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
    ]
