"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY", default="django-insecure--@dwp8=_9jtp31fk5uenu^qd1_py7bav=tp$(1^v!cux8$d5xz"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())

CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "axes",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "apps.common",
    "apps.accounts",
    "apps.producers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Sirve los estáticos en producción (admin incluido); va justo tras SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.common.middleware.ApiNoStoreMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# En despliegue se pasa DATABASE_URL (convención de 12-factor, la soportan la mayoría
# de proveedores); en local no existe esa variable y se arma la conexión con las
# DB_* del .env de cada quien.
DATABASE_URL = config("DATABASE_URL", default="")
if DATABASE_URL:
    DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST", default="localhost"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        # Por defecto compara con username, nombre y correo; el documento también es un dato
        # que un tercero puede conocer.
        "OPTIONS": {
            "user_attributes": ("email", "first_name", "last_name", "identity_document"),
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "apps.accounts.validators.MaximumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"

# Cuántos proxies de confianza hay delante de la app. DRF lo usa (NUM_PROXIES) para leer la IP
# real desde X-Forwarded-For contando desde la derecha; con 0 se usa REMOTE_ADDR tal cual.
TRUSTED_PROXY_COUNT = config("TRUSTED_PROXY_COUNT", default=0, cast=int)

AUTHENTICATION_BACKENDS = [
    # axes va primero: corta el intento si la pareja usuario + IP está bloqueada.
    "axes.backends.AxesStandaloneBackend",
    # Deja pasar cuentas inactivas con la contraseña correcta para poder avisarles que lo
    # están; log_in las rechaza igual (en el admin lo hace su formulario de acceso).
    "django.contrib.auth.backends.AllowAllUsersModelBackend",
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=15)
# Bloquear la pareja y no el usuario solo evita que alguien bloquee una cuenta ajena
# conociendo su correo.
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = True
# Un intento durante el bloqueo no lo alarga: el bloqueo dura exactamente AXES_COOLOFF_TIME.
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False
# axes toma por defecto USERNAME_FIELD ("email") como clave de las credenciales, pero
# authenticate() y lockout_identifier las manejan como "username". Sin esto el identificador
# sale vacío al comprobar el bloqueo y al reiniciar el conteo, y el bloqueo nunca se aplica.
AXES_USERNAME_FORM_FIELD = "username"
AXES_USERNAME_CALLABLE = "apps.accounts.axes.lockout_identifier"
# La auditoría de accesos la lleva AuthenticationEvent, sin correos ni IP.
AXES_DISABLE_ACCESS_LOG = True
# axes lee la IP con la misma función que los límites de solicitudes de DRF: sin proxy usa
# REMOTE_ADDR y con proxies cuenta solo los saltos de confianza desde la derecha de
# X-Forwarded-For. Así las dos ven siempre la misma IP y el cliente no puede inventarse una
# para esquivar el bloqueo.
AXES_CLIENT_IP_CALLABLE = "apps.accounts.axes.client_ip"
# axes guarda los parámetros del POST en claro salvo estos; con peticiones de formulario
# llegarían el correo y el documento. También los enmascara en sus logs.
AXES_SENSITIVE_PARAMETERS = ["username", "ip_address", "email", "identity_document"]
# Sin el modo detallado, los logs de axes solo nombran los parámetros del bloqueo (usuario e IP),
# que la lista de arriba enmascara, y no el user-agent. Tras un login exitoso axes nombra al
# usuario por su correo: "username" no puede salir de esa lista.
AXES_VERBOSE = False

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["apps.accounts.authentication.CookieJWTAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "EXCEPTION_HANDLER": "apps.common.exceptions.api_exception_handler",
    "NUM_PROXIES": TRUSTED_PROXY_COUNT,
    "DEFAULT_THROTTLE_RATES": {
        "login": "20/min",
        "password_reset": "5/hour",
        "password_reset_identifier": "5/hour",
        "password_reset_confirm": "5/hour",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # Al cambiar la contraseña, todos los tokens de acceso ya emitidos dejan de servir.
    "CHECK_REVOKE_TOKEN": True,
    "UPDATE_LAST_LOGIN": False,
    "USER_ID_FIELD": "id",
    "SIGNING_KEY": config("AUTH_JWT_SIGNING_KEY", default=SECRET_KEY),
    "AUDIENCE": "ruta-del-cacao-web",
    "ISSUER": "ruta-del-cacao-api",
}
PASSWORD_RESET_TIMEOUT = 60 * 30
AUTH_ACCESS_COOKIE = "cacao_access"
AUTH_REFRESH_COOKIE = "cacao_refresh"
AUTH_COOKIE_SECURE = config("AUTH_COOKIE_SECURE", default=not DEBUG, cast=bool)
AUTH_COOKIE_SAMESITE = config("AUTH_COOKIE_SAMESITE", default="Lax")
CSRF_COOKIE_SECURE = AUTH_COOKIE_SECURE
CSRF_COOKIE_SAMESITE = AUTH_COOKIE_SAMESITE

CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", default="", cast=Csv())
CORS_ALLOW_CREDENTIALS = True


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
# collectstatic junta aquí todo (admin incluido) para que WhiteNoise lo sirva.
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    # Comprime y versiona (hash en el nombre) los estáticos en producción.
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}


# Seguridad detrás de un proxy que termina TLS (activa solo fuera de DEBUG)
if not DEBUG:
    # El proxy reenvía por HTTP con esta cabecera; sin esto Django no sabe que el
    # request original fue HTTPS y puede entrar en loop de redirect.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILER_BACKEND = config(
    "MAILER_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)
MAILER_OPTIONS = {}
if MAILER_BACKEND == "anymail.backends.resend.EmailBackend":
    MAILER_OPTIONS = {"api_key": config("RESEND_API_KEY")}
elif MAILER_BACKEND == "django.core.mail.backends.smtp.EmailBackend":
    MAILER_OPTIONS = {
        "host": config("MAILER_HOST"),
        "port": config("MAILER_PORT", default=587, cast=int),
        "username": config("MAILER_USERNAME"),
        "password": config("MAILER_PASSWORD"),
        "use_tls": config("MAILER_USE_TLS", default=True, cast=bool),
    }

MAILERS = {
    "default": {
        "BACKEND": MAILER_BACKEND,
        "OPTIONS": MAILER_OPTIONS,
    }
}

FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="no-reply@rutadelcacao.local")
