# Generated by Django 6.1.1 on 2026-09-26 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producers", "0005_alter_producer_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_normalized", models.CharField(editable=False, max_length=200)),
                ("department_code", models.CharField(max_length=2)),
                ("municipality_code", models.CharField(max_length=5)),
                ("details", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("area_hectares", models.DecimalField(decimal_places=2, max_digits=10)),
                ("altitude_masl", models.IntegerField()),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="farms",
                        to="producers.producer",
                    ),
                ),
            ],
        ),
    ]
