# Generated by Django 6.1.1 on 2026-09-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
        ("producers", "0005_alter_producer_document_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                fields=("producer", "name_normalized"),
                name="farms_producer_name_normalized_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.CheckConstraint(
                condition=models.Q(("area_hectares__gt", 0)), name="farms_area_hectares_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="farms_latitude_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="farms_longitude_in_range",
            ),
        ),
    ]
