# Generated by Django 6.1.1 on 2026-09-26 03:11

import farms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_farm_farms_producer_name_normalized_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="altitude_masl",
            field=models.IntegerField(validators=[farms.validators.validate_altitude]),
        ),
        migrations.AlterField(
            model_name="farm",
            name="area_hectares",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[farms.validators.validate_positive_area],
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="latitude",
            field=models.DecimalField(
                decimal_places=7, max_digits=9, validators=[farms.validators.validate_latitude]
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="longitude",
            field=models.DecimalField(
                decimal_places=7, max_digits=10, validators=[farms.validators.validate_longitude]
            ),
        ),
    ]
