# Generated by Django 6.1.1 on 2026-10-03 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plots", "0002_plot_deletion_and_surviving_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CacaoVariety",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("name_normalized", models.CharField(editable=False, max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name_normalized"],
                "permissions": [
                    (
                        "manage_cacaovariety",
                        "Puede registrar, editar, activar y desactivar variedades de cacao",
                    )
                ],
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name_normalized",), name="crops_variety_name_normalized_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CacaoVarietyAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("variety_ref", models.UUIDField(db_index=True)),
                ("variety_name", models.CharField(max_length=60)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Variedad registrada"),
                            ("updated", "Variedad actualizada"),
                            ("status_changed", "Estado de variedad modificado"),
                            ("deleted", "Variedad eliminada"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cacao_variety_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="crops.cacaovariety",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlotCharacterization",
            fields=[
                (
                    "plot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="characterization",
                        serialize=False,
                        to="plots.plot",
                    ),
                ),
                ("planting_date", models.DateField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("establishment", "Establecimiento o formación"),
                            ("early_production", "Inicio de producción"),
                            ("full_production", "Producción estable"),
                            ("renovation", "Renovación o rehabilitación"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "management_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conventional", "Convencional"),
                            ("organic", "Orgánico"),
                            ("in_transition", "En transición a orgánico"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "shade_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "A plena exposición"),
                            ("temporary", "Sombra temporal"),
                            ("permanent", "Sombra permanente"),
                            ("mixed", "Temporal y permanente"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "permissions": [
                    (
                        "change_plotcharacterization",
                        "Puede registrar y editar la caracterización de parcelas",
                    )
                ],
                "default_permissions": (),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("planting_date__day", 1)),
                        name="crops_planting_date_first_of_month",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlotCharacterizationAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Caracterización registrada"),
                            ("updated", "Caracterización actualizada"),
                        ],
                        max_length=32,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plot_characterization_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="characterization_audit_events",
                        to="plots.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="PlotCharacterizationVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tree_count", models.PositiveIntegerField()),
                (
                    "characterization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varieties",
                        to="crops.plotcharacterization",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="characterization_rows",
                        to="crops.cacaovariety",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("characterization", "variety"),
                        name="crops_characterization_variety_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("tree_count__gt", 0)), name="crops_tree_count_positive"
                    ),
                ],
            },
        ),
    ]
