# Generated by Django 6.1.1 on 2026-09-29 04:28

import apps.farms.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("producers", "0007_enable_unaccent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_normalized", models.CharField(editable=False, max_length=200)),
                ("department_code", models.CharField(max_length=2)),
                ("municipality_code", models.CharField(max_length=5)),
                ("details", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "area_hectares",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[apps.farms.validators.validate_positive_area],
                    ),
                ),
                (
                    "altitude_masl",
                    models.IntegerField(validators=[apps.farms.validators.validate_altitude]),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        max_digits=9,
                        validators=[apps.farms.validators.validate_latitude],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        max_digits=10,
                        validators=[apps.farms.validators.validate_longitude],
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="farms",
                        to="producers.producer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Finca creada"),
                            ("updated", "Finca actualizada"),
                            ("status_changed", "Estado de finca modificado"),
                        ],
                        max_length=32,
                    ),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="farm_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.UniqueConstraint(
                fields=("producer", "name_normalized"),
                name="farms_producer_name_normalized_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.CheckConstraint(
                condition=models.Q(("area_hectares__gt", 0)), name="farms_area_hectares_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="farms_latitude_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="farm",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="farms_longitude_in_range",
            ),
        ),
    ]
