# Generated by Django 6.1.1 on 2026-09-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={"default_permissions": ("view", "add", "change")},
        ),
    ]
