# Generated by Django 6.1.1 on 2026-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_farm_permissions_without_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
