# Generated by Django 6.1.1 on 2026-10-01 01:31

from django.db import migrations

NAMES = {
    "view_farm": "Puede consultar fincas",
    "add_farm": "Puede registrar fincas",
    "change_farm": "Puede editar, activar y desactivar fincas",
}


def rename_existing_permissions(apps, schema_editor):
    # Django solo crea los permisos que faltan; los que ya existían con el nombre en inglés
    # que genera por defecto se quedarían así sin este paso. En una base nueva no hay filas
    # todavía y no hace nada.
    Permission = apps.get_model("auth", "Permission")
    for codename, name in NAMES.items():
        Permission.objects.filter(
            content_type__app_label="farms", content_type__model="farm", codename=codename
        ).update(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("farms", "0003_farm_captured_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={
                "default_permissions": (),
                "permissions": [
                    ("view_farm", "Puede consultar fincas"),
                    ("add_farm", "Puede registrar fincas"),
                    ("change_farm", "Puede editar, activar y desactivar fincas"),
                ],
            },
        ),
        migrations.RunPython(rename_existing_permissions, migrations.RunPython.noop),
    ]
