# Generated by Django 6.1.1 on 2026-10-09 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plots", "0002_plot_deletion_and_surviving_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgriculturalActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("pruning", "Poda"),
                            ("fertilization", "Fertilización"),
                            ("irrigation", "Riego"),
                            ("weed_control", "Control de malezas"),
                            ("phytosanitary_monitoring", "Monitoreo fitosanitario"),
                            ("phytosanitary_control", "Control fitosanitario"),
                            ("cleaning_or_liming", "Limpieza o encalado"),
                            ("inventory", "Inventario"),
                            ("other", "Otro"),
                        ],
                        max_length=32,
                    ),
                ),
                ("other_description", models.CharField(blank=True, max_length=80, null=True)),
                ("scheduled_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("scheduled", "Programada"), ("done", "Realizada")],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("done_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agricultural_activities",
                        to="plots.plot",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "activity_type", "id"],
                "permissions": [
                    ("view_agriculturalactivity", "Puede consultar actividades agrícolas"),
                    ("add_agriculturalactivity", "Puede programar actividades agrícolas"),
                    (
                        "change_agriculturalactivity",
                        "Puede editar y reprogramar actividades agrícolas",
                    ),
                    (
                        "complete_agriculturalactivity",
                        "Puede registrar la realización de actividades agrícolas",
                    ),
                    (
                        "delete_agriculturalactivity",
                        "Puede eliminar actividades agrícolas programadas por error",
                    ),
                ],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AgriculturalActivityAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("activity_ref", models.UUIDField(db_index=True)),
                ("plot_ref", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Actividad programada"),
                            ("updated", "Actividad actualizada"),
                            ("completed", "Realización registrada"),
                            ("deleted", "Actividad eliminada"),
                        ],
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("changes", models.JSONField(default=dict)),
                (
                    "activity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="activities.agriculturalactivity",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agricultural_activity_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="agriculturalactivity",
            index=models.Index(fields=["plot", "scheduled_date"], name="activities_plot_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="agriculturalactivity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activity_type", "other"),
                        ("other_description__isnull", False),
                        models.Q(("other_description", ""), _negated=True),
                    ),
                    models.Q(
                        models.Q(("activity_type", "other"), _negated=True),
                        ("other_description__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="activities_other_description_only_with_other",
            ),
        ),
        migrations.AddConstraint(
            model_name="agriculturalactivity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", False),
                        ("done_date__isnull", False),
                        ("status", "done"),
                    ),
                    models.Q(
                        ("completed_at__isnull", True),
                        ("done_date__isnull", True),
                        ("status", "scheduled"),
                    ),
                    _connector="OR",
                ),
                name="activities_completion_data_only_when_done",
            ),
        ),
    ]
